# example: ansible-playbook add-serverpilot.yml --extra-vars "fresh_server_ip=1.2.3.4, server_name=somename"
# https://github.com/ServerPilot/API#connect-a-new-server
---

- name: Add ServerPilot server and return info 
  hosts: 127.0.0.1
  vars: 
    sp_api_base: "https://api.serverpilot.io/v1"
    server_name: "{{ server_name }}"
  vars_files:  
    - vault.yml
  gather_facts: no
  tasks:
    - name: Add server record to ServerPilot
      uri:
        url: "{{ sp_api_base }}/servers"
        method: POST
        user: "{{ sp_client_id }}"
        password: "{{ sp_api_key }}"
        body: "{ 'name':'{{ server_name }}', 'enable_ssh_password_auth':true}"
        body_format: json
        status_code: 200, 409
        timeout: 10
        force_basic_auth: true
      register: sp_server_info # if the server already exists, sp_server_info.json.data will not be a thing

    - name: Pass along server info to next play
      set_fact: 
        action_id: "{{ sp_server_info.json.actionid }}"
        server_id: "{{ sp_server_info.json.data.id }}"
        apikey: "{{ sp_server_info.json.data.apikey  }}"
      when: sp_server_info.json.data is defined

    - name: Pass the API base to next play  
      set_fact: 
        sp_api_base: "{{ sp_api_base }}"

- name: Connect ServerPilot to a freshly created Ubuntu VPS and do some post-install configuration
  hosts: "{{ fresh_server_ip }}"
  vars: 
    phps: ["7.3", "7.2", "7.1", "7.0", "5.6"]
    phps_mcrypt: ["7.3", "7.2"]
  vars_files:  
    - vault.yml
  gather_facts: no
  become: true
  become_user: root  
  tasks:
    - name: sudo apt-get update 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install packages ServerPilot needs
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - wget
        - ca-certificates

    - name: Fetch the ServerPilot installer 
      command: wget -nv -O serverpilot-installer https://download.serverpilot.io/serverpilot-installer
      when: hostvars['localhost']['server_id'] is defined

    - name: Run installer 
      command: sh serverpilot-installer --server-id={{hostvars['localhost']['server_id']|quote}} --server-apikey={{hostvars['localhost']['apikey']|quote}}
      when: hostvars['localhost']['server_id'] is defined

    # Make sure ServerPilto totally finishhes before doing the post-flight config...
    - name: Make sure ServerPilot finishes install before proceeding
      uri:
        url: "hostvars['localhost']['sp_api_base']/actions/{{hostvars['localhost']['action_id']}}"
        method: GET
        user: "{{ sp_client_id }}"
        password: "{{ sp_api_key }}"
        body_format: json
        status_code: 200
        timeout: 10
        force_basic_auth: true
      register: result
      delay: 10
      retries: 30
      until: result.json.data.status == success
      when: hostvars['localhost']['action_id'] is defined

    - name: Configure timezone 
      timezone:
        name: America/Chicago
      register: timezone

    - name: "Restart server after timezone config"
      reboot:
      when: timezone.changed

    - name: Add htop
      apt:
        name: htop

    - name: Turn off MySQL strict mode
      copy:
        dest: "/etc/mysql/conf.d/disable_strict_mode.cnf"
        content: |
          [mysqld]
          sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

    - name: Add htop
      apt:
        name: htop

    - name: Add gcc, make, autoconf, libc-dev, pkg-config
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - gcc
        - make 
        - autoconf 
        - libc-dev 
        - pkg-config

    - name: Add htop
      apt:
        name: libmagickwand-dev

    - name: Install Imagick on all PHP versions
      command: pecl{{ item }}-sp install imagick
      with_items: "{{ phps }}"
      ignore_errors: true

    - name: Create a configuration file for imagick
      command: bash -c "echo extension=imagick.so > /etc/php{{ item }}-sp/conf.d/imagick.ini"
      with_items: "{{ phps }}"

    - name: Install libmcrypt-dev
      apt:
        name: libmcrypt-dev

    - name: Install mcrypt
      command: pecl{{ item }}-sp install --nodeps mcrypt-snapshot
      with_items: "{{ phps_mcrypt }}"
      ignore_errors: true

    - name: Create a configuration file for libmcrypt-dev
      command: bash -c "echo extension=mcrypt.so > /etc/php{{ item }}-sp/conf.d/mcrypt.ini"
      with_items: "{{ phps_mcrypt }}"

    - name: Restart PHP
      service:
        name: "php{{ item }}-fpm-sp"
        state: restarted
      with_items: "{{ phps }}"

